git:
    quiet: true
    submodules: true
    depth: 50
language: java
# uncomment to always install latest oracle java8 jdk:
#addons:
#    apt:
#        packages:
#         - oracle-java8-installer
jdk:
    - oraclejdk8
before_install:
    - "chmod +x gradlew"
    - "./gradlew cleanLoomBinaries cleanLoomMappings clean"

script:
    - "./gradlew build"

before_cache:
    - find $HOME/.gradle/ -name '*.lock' -print -exec rm -f {} \;

cache:
    directories:
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"

before_deploy:
    - echo "deploying to NerdHub Maven:"
    - echo $(ls  | tr '\n' ', ')

deploy:
    -   provider: script
        script: "./gradlew publish"
        on:
            repo: GlassPane/Mesh
            branch: master
        skip_cleanup: true

    # if commit tag is created, deploy to curseforge
    -   provider: script
        script: "./gradlew curseforge"
        skip_cleanup: true
        target_commitsh: $TRAVIS_TAG
        on:
            repo: GlassPane/Mesh
            tags: true
            branch: master
