name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Setup ENV
        run: echo "TAG=${GITHUB_REF:10}" >> $GITHUB_ENV
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble jar with Gradle
        env:
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: ./gradlew assemble
      - name: Upload release assets to Onyx Maven
        id: publish_release_assets
        run: ./gradlew publish
        env:
          BUILD_TIME: ${{ steps.current-time.outputs.formattedTime }}
          BUILD_NUMBER: ${{ github.run_number }}
          MAVEN_UPLOAD_URL: ${{ secrets.ONYX_MAVEN_UPLOAD_URL }}
          MAVEN_UPLOAD_USER: ${{ secrets.ONYX_MAVEN_USERNAME }}
          MAVEN_UPLOAD_PASSWORD: ${{ secrets.ONYX_MAVEN_ACCESS_TOKEN }}
          MODRINTH_USER: ${{ secrets.MODRINTH_USER }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Upload release assets
        id: upload_release_assets
        uses: AButler/upload-release-assets@v2.0
        with:
          release-tag: ${{ env.TAG }}
          repo-token: ${{ github.token }}
          files: 'build/libs/*[!-dev].jar'
