name: Upload Release Artifacts

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Get current time
        uses: srfrnk/current-time@master
        id: current-time
        with:
          format: YYYYMMDDHHmmss
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Setup ENV
        run: echo ::set-env name=TAG::$(echo ${GITHUB_REF:10})
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Assemble jar with Gradle
        env:
          BUILD_NUMBER: ${{ steps.current-time.outputs.formattedTime }}
        run: ./gradlew clean assemble
      - name: Upload release assets
        id: upload-release-asset
        uses: AButler/upload-release-assets@v2.0
        with:
          release-tag: ${{ env.TAG }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: 'build/libs/*[!-dev].jar'
